[[Basic]]
name = "basic"
threads = [1, 2, 4, 8, 32]
time = 3
workload = ["ReadOnly", "InsertOnly", "UpdateOnly", "ScanOnly"] 
index_type = ["Flurry", "ART"]

[[Scan]]
name = "scan"
threads = [1, 2, 4, 8]
time = 3
